table<-read.table("household_power_consumption.txt", header=T, sep=";", na.string= "?")
table$Date <- as.Date(table$Date, "%d/%m/%Y")
subframe<-subset(table, Date==as.Date("2007-02-01") | Date==as.Date("2007-02-02"))
png("plot1.png",)
hist(subframe$Global_active_power, breaks = 12, col="red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()